name: deploy-auth


on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker biuld -t oluwatobi123/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD   
        env:
          DOCKET_USERNAME: ${{ secrets.DOCKET_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKET_PASSWORD }}
      - run: docket push oluwatobi123/auth
     
                                                                                                                                    
