name: deploy-auth


on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t oluwatobi123/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD   
        env:
          DOCKET_USERNAME: ${{ secrets.DOCKET_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKET_PASSWORD }}
      - run: docket push oluwatobi123/auth
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl
